// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUeUKs3fE85qXUcG4vwqVpA5tot3tdhnU',
    appId: '1:480708271782:web:9abf5456fab9227052de67',
    messagingSenderId: '480708271782',
    projectId: 'fintech-app-e8e33',
    authDomain: 'fintech-app-e8e33.firebaseapp.com',
    storageBucket: 'fintech-app-e8e33.firebasestorage.app',
    measurementId: 'G-DD09JM9M3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACi_N8llffCbseZCIs-CtjgX62KffL8dQ',
    appId: '1:480708271782:android:747417075cd89c8c52de67',
    messagingSenderId: '480708271782',
    projectId: 'fintech-app-e8e33',
    storageBucket: 'fintech-app-e8e33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyMCizWPM-jCb9iieKE8HBBFuCxPxqe5M',
    appId: '1:480708271782:ios:31cb3d19f41ac14a52de67',
    messagingSenderId: '480708271782',
    projectId: 'fintech-app-e8e33',
    storageBucket: 'fintech-app-e8e33.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyMCizWPM-jCb9iieKE8HBBFuCxPxqe5M',
    appId: '1:480708271782:ios:31cb3d19f41ac14a52de67',
    messagingSenderId: '480708271782',
    projectId: 'fintech-app-e8e33',
    storageBucket: 'fintech-app-e8e33.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUeUKs3fE85qXUcG4vwqVpA5tot3tdhnU',
    appId: '1:480708271782:web:d48972de572eaf1652de67',
    messagingSenderId: '480708271782',
    projectId: 'fintech-app-e8e33',
    authDomain: 'fintech-app-e8e33.firebaseapp.com',
    storageBucket: 'fintech-app-e8e33.firebasestorage.app',
    measurementId: 'G-NKB4EQM2FD',
  );
}
